### ISSUE TITLE
segfault in notify_stack_set_location()

### ISSUE THREAD

**Issue by brianjmurrell** [mate-desktop/mate-notification-daemon#39] opened 2014-10-08 13:14 UTC
Per the downstream bug report at https://bugzilla.redhat.com/show_bug.cgi?id=1142441 I'm seeing a repeated segfault in notify_stack_set_location().

Full backtrace can be found in https://bugzilla.redhat.com/attachment.cgi?id=938192

**Comment by NiceandGently** [comment] 2015-01-13 11:19
downstream report is closed and update is in stable repo.

**Comment by monsta** [comment] 2015-03-17 11:36
@brianjmurrell: the fix has been merged and released, did it fix the problem for you?

**Comment by brianjmurrell** [comment] 2015-03-17 12:46
@monsta: I guess a bit of time (and the absence of any more crashes) will tell.  :-)

Thanks much for the fix!  Much appreciated.

**Comment by NiceandGently** [comment] 2015-03-17 12:52
@brianjmurrell 
Can you please close the report?

**Comment by NiceandGently** [comment] 2015-05-20 15:47
@flexiondotorg 
patch is for a long time in upstream build and confirmed as working
Please close it

**Comment by monsta** [comment] 2015-07-07 13:25
@flexiondotorg: yes please close for the reasons stated above

**Closed** 2015-07-07 13:41 UTC
