### ISSUE TITLE
Orca screen reader not speaking pop-up notifications

### ISSUE THREAD

**Issue by the-kyle** [mate-desktop/mate-notification-daemon#30] opened 2014-03-12 01:05 UTC
At-spi doesn't seem to be picking up the text of pop-up notifications. For example, in system -> preferences -> pop-up notifications, Orca doesn't speak the text of the notification that pops up when activating the preview button. Replacing mate-notification-daemon with notify-osd does appear to help in most cases, but it's not 100%, and removes the option to set where pop-up notifications appear on screen, as well as all options associated with pop-up notifications including the preview.

**Comment by infirit** [comment] 2015-08-26 22:20
I can make the notification read by changing Gtk+'s window from ``GTK_WINDOW_POPUP `` to ``GTK_WINDOW_TOPLEVEL``. But I do not understand why windows of type ``GTK_WINDOW_POPUP `` are ignored by orca :confused:.

See below for quick hack to change the window type for the __standard__ theme.

```diff
diff --git a/src/themes/standard/theme.c b/src/themes/standard/theme.c
index 09aa628..cc0bd75 100644
--- a/src/themes/standard/theme.c
+++ b/src/themes/standard/theme.c
@@ -640,7 +640,8 @@ GtkWindow* create_notification(UrlClickedCb url_clicked)
 	windata->urgency = URGENCY_NORMAL;
 	windata->url_clicked = url_clicked;
 
-	win = gtk_window_new(GTK_WINDOW_POPUP);
+	win = gtk_window_new(GTK_WINDOW_TOPLEVEL);
+	gtk_window_set_decorated (win, FALSE);
 	windata->win = win;
 
 	windata->composited = FALSE;
```

**Comment by monsta** [comment] 2015-11-16 08:11
@coffeeking: can you please check if it still happens in 1.12?

**Comment by coffeeking** [comment] 2015-11-16 08:27
Confirmed. This does indeed still happen in 1.12. In addition, replacing mate's notification-daemon with notify-osd no longer works

**Comment by monsta** [comment] 2015-11-16 09:03
Ok, what can be done about it then - in regards to what's written above about ```GTK_WINDOW_POPUP```?

**Comment by coffeeking** [comment] 2015-11-16 09:07
I'm not completely sure, but if changing the window style works, I'd suggest doing so for all the provided notification themes, standard, nadoka, slider, coko, etc. I'll also inquire on the orca list to see if joanmeri diggs can find out why the notifications aren't working like they should

**Comment by lukefromdc** [comment] 2016-06-23 18:26
Seems to me a direct audio notification option (possibly by a special theme engine hooked into Orca's audio system) would be the best possible approach to this. No idea how to code it though, and when I tried to test Orca on my system  (a hacked Debian Unstable full of locally compiled stuff) some kind of audio bugs made it impossible to get any audio from it.

**Comment by raveit65** [comment] 2016-06-29 14:37
@coffeeking 
Can you test https://github.com/mate-desktop/mate-notification-daemon/commit/2111df36e03c9d1dbb5529594ebce42cf9e39f85
which is in 1.15.1 release.
I made header and body translatable, hopefully this was the issue

**Comment by coffeeking** [comment] 2016-06-29 17:41
hi
I'm so sorry, I never did close this one, did I. I fixed this ages ago.
All it took was adding mate's notification daemon to the default script,
essentially telling orca that anything coming in from that program was a
notification and to read it. For some reason orca wasn't noticing that
before. This means that all mate versions have accessible notifications,
at least everything since 1.8 does. However, I will test this commit to
see what it does.
Thanks
Kendell Clark


raveit65 wrote:

**Comment by monsta** [comment] 2016-06-29 18:31
Oh. So we don't need to try to change window style? :smile:

**Comment by coffeeking** [comment] 2016-06-29 22:23
hi
It's not necessary to allow orca to read it, but this commit does make
orca read the notifications better. Before this orca would occasionally
miss a notification or two, but with this change it doesn't miss them,
so it's good that you made it.
Thanks
Kendell Clark


monsta wrote:

**Comment by raveit65** [comment] 2016-06-29 22:57
FIne,
i will backport this commit to 1.14 branch

**Comment by raveit65** [comment] 2016-06-29 23:05
> Oh. So we don't need to try to change window style? :smile:

I think the fix for notification window hint did also improve the situation.

**Comment by monsta** [comment] 2016-06-30 08:40
Ok, so can we close this now, or is there something else to do here?

**Comment by raveit65** [comment] 2016-06-30 18:29
@coffeeking 
I've releases 1.14.1 with that improvement.
I hope you agree with closing this issue, if not mention it here and we will reopen it.

**Closed by raveit65** 2016-06-30 18:29 UTC
Labels: feature request
